### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by tmrudolp** [redcanaryco/mac-monitor#1]
Hi Brandon and Red Canary Team,

are you planing to make the package available in homebrew ?

kind regards

**Comment by Brandon7CC** [comment]
Hi @tmrudolp thank you for the excellent suggestion! Let me look into this and get back to you

**Comment by Brandon7CC** [comment]
PR submitted! Waiting on merge -- thank you for the excellent suggestion! https://github.com/Homebrew/homebrew-cask/pull/146071

**Comment by Brandon7CC** [comment]
`brew install --cask red-canary-mac-monitor`

**Comment by tmrudolp** [comment]
Awesome Brandon 👏
