### ISSUE TITLE
Clicking on parent items in the subtree removes child items

### ISSUE THREAD

**Issue by AndrewMohawk** [redcanaryco/mac-monitor#16]
**Describe the bug**
If I am exploring an event with a subtree when I traverse up the subtree by click on the parent event the child trees disappear without a way to get them back.

**Expected behavior**
Clicking on the parent does not remove the subtree or there is a way for me to get it back without re-opening the event view

**To Reproduce**
1. Open Child item
2. Click on any parent in the subtree
3. Child items are removed

**Screenshots**
N/A

**Comment by Brandon7CC** [comment]
This one is a feature "pruning the tree"! 😉  We enable users to get back by clicking the target process button in the top right!
<img width="959" alt="Screenshot 2023-04-17 at 1 43 49 PM" src="https://user-images.githubusercontent.com/22716543/232606551-0ef26bc1-fd8a-4e4d-86cf-8ac2cf5b82f8.png">

**Comment by AndrewMohawk** [comment]
Doh. Thank you, Didn't notice that!
