### ISSUE TITLE
Can not open source ?

### ISSUE THREAD

**Issue by Dark177y** [redcanaryco/mac-monitor#2]
I want to learn more from it, and see how can i help to add more features

**Comment by mgraeber-rc** [comment]
Hi, @Dark177y. There are no current plans to open source this tool. Enjoy it and please offer any feedback/suggestions that you may have!

**Comment by Brandon7CC** [comment]
Hi @Dark177y! Like Matt said we currently don't have plans to open source this project, but we'd be more than happy to look into providing more documentation / blogs where we can (at request). This is a big piece of software with lots of exciting things to talk about!
