### ISSUE TITLE
Mojave Support?

### ISSUE THREAD

**Issue by dhyanKaro** [redcanaryco/mac-monitor#34]
Would be nice. Get that 10.14... good stuff.

**Comment by Brandon7CC** [comment]
Hi @dhyanKaro and happy Saturday!

Mac Monitor relies on Apple's [Endpoint Security APIs](https://developer.apple.com/documentation/endpointsecurity) as a data source which was released with macOS 10.15 Catalina. Mojave support is unfortunately not possible here.

Thank you for asking though and let me know if you have any more questions! 

@mgraeber-rc would you mind closing this out for me :)
