### ISSUE TITLE
Artifact Filtering -> ES event list not in Sync with Subscribed events

### ISSUE THREAD

**Issue by theevilbit** [redcanaryco/mac-monitor#5]
**Describe the bug**
When I subscribe to a new event, it should appear under Artifact Filtering -> ES events, but it only appears if I disable/enable it.

**Expected behavior**
See above

**To Reproduce**
1. Enable artifact filtering
2. Subscribe to a new event in Settings
3. The new event won't appear in Artifact Filtering -> ES events

**Platform specifics (please complete the following information):**
 - macOS version 13.3.1
 - Architecture Intel
- Version 1.0.1 (1)

**Comment by Brandon7CC** [comment]
100% correct! I've found myself doing similar things during analysis. Should be an easier add!

**Comment by Brandon7CC** [comment]
Fixed in `v1.0.3` thank you @theevilbit! Please note that when you unsubscribe from an even that event will *not* be removed from the filter set because it led to a strange user experience
