### ISSUE TITLE
Clicking on the col headings does not sort them

### ISSUE THREAD

**Issue by AndrewMohawk** [redcanaryco/mac-monitor#9]
**Describe the bug**
When clicking on the column headings ( eg. Event Type, Target, Effective User, Source process) I would expect these columns to then sort alphabetically, but the heading title just responds like a button without any effect on the table

**Expected behavior**
Clicking on col headings rotates through sorting alphabetically, reverse alphabetically and none/default

**To Reproduce**
1. Click col heading

**Platform specifics (please complete the following information):**
 - macOS version: `13.2.1`
 - Architecture: Apple Silicon

**Comment by Brandon7CC** [comment]
Hey @AndrewMohawk! This is actually just a feature I didn't have time to implement. I'll switch this over to a "feature request" and link to #7. Thank you for the suggestion!

**Comment by Brandon7CC** [comment]
Closing as duplicate #7
